[Metadata]
Name=Moss and Fern
Version=2.0
Author=ep-o1
Description=Moss & Fern theme matching system palette (colors.nix)
ScaleWithDPI=True

[InputPanel]
Font=Sarasa UI SC 14
NormalColor=#b5b9ae
HighlightCandidateColor=#1c1f1c
HighlightColor=#8e9878
HighlightBackgroundColor=#8e9878
Spacing=6

[InputPanel/TextMargin]
Left=12
Right=12
Top=8
Bottom=8

[InputPanel/Background]
Color=#1c1f1c
BorderColor=#343734
BorderWidth=1
Alpha=255

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#8e9878

[InputPanel/Highlight/Margin]
Left=12
Right=12
Top=8
Bottom=8

[InputPanel/ContentMargin]
Left=4
Right=4
Top=4
Bottom=4

[Menu]
Font=Sarasa UI SC 12
NormalColor=#b5b9ae
HighlightCandidateColor=#1c1f1c
Spacing=4

[Menu/Background]
Color=#1c1f1c
BorderColor=#343734
BorderWidth=1
Alpha=255

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=4
Right=4
Top=4
Bottom=4

[Menu/Highlight]
Color=#8e9878

[Menu/Highlight/Margin]
Left=10
Right=10
Top=6
Bottom=6

[Menu/Separator]
Color=#343734
